### ISSUE TITLE
ABI breakage causes kiwix-tools to not compile

### ISSUE THREAD

**Issue by juuz0** [kiwix/kiwix-tools#645]
```
/usr/bin/ld: /usr/local/lib/x86_64-linux-gnu/libkiwix.so: undefined reference to `zim::Item::getPath[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
```

I suspect this issue was introduced in: https://github.com/openzim/libzim/pull/836

**Comment by mgautierfr** [comment]
Which version of libzim do you using ?
How do you compile kiwix-tools ?

---

openzim/libzim#836 is a ABI breakage, not a API. So recompiling should be ok.

**Comment by juuz0** [comment]
> Which version of libzim do you using ?

latest main branch

>  How do you compile kiwix-tools ?

the usual README way.

```
meson . build
sudo ninja -C build install
```

Full error:
```
[3/7] Linking target src/searcher/kiwix-search
FAILED: src/searcher/kiwix-search 
c++  -o src/searcher/kiwix-search src/searcher/kiwix-search.p/kiwix-search.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-rpath,/usr/local/lib/x86_64-linux-gnu -Wl,-rpath-link,/usr/local/lib/x86_64-linux-gnu -pthread -Wl,--start-group /usr/local/lib/x86_64-linux-gnu/libkiwix.so /usr/local/lib/x86_64-linux-gnu/libzim.so /usr/lib/x86_64-linux-gnu/liblzma.so /usr/lib/x86_64-linux-gnu/libzstd.so /usr/lib/x86_64-linux-gnu/libicui18n.so /usr/lib/x86_64-linux-gnu/libicuuc.so /usr/lib/x86_64-linux-gnu/libicudata.so /usr/lib/x86_64-linux-gnu/libpugixml.so /usr/lib/x86_64-linux-gnu/libcurl.so /usr/lib/x86_64-linux-gnu/libmicrohttpd.so /usr/lib/x86_64-linux-gnu/libxapian.so -Wl,--end-group
/usr/bin/ld: /usr/local/lib/x86_64-linux-gnu/libkiwix.so: undefined reference to `zim::Item::getPath[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
[5/7] Linking target src/manager/kiwix-manage
FAILED: src/manager/kiwix-manage 
c++  -o src/manager/kiwix-manage src/manager/kiwix-manage.p/kiwix-manage.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-rpath,/usr/local/lib/x86_64-linux-gnu -Wl,-rpath-link,/usr/local/lib/x86_64-linux-gnu -pthread -Wl,--start-group /usr/local/lib/x86_64-linux-gnu/libkiwix.so /usr/local/lib/x86_64-linux-gnu/libzim.so /usr/lib/x86_64-linux-gnu/liblzma.so /usr/lib/x86_64-linux-gnu/libzstd.so /usr/lib/x86_64-linux-gnu/libicui18n.so /usr/lib/x86_64-linux-gnu/libicuuc.so /usr/lib/x86_64-linux-gnu/libicudata.so /usr/lib/x86_64-linux-gnu/libpugixml.so /usr/lib/x86_64-linux-gnu/libcurl.so /usr/lib/x86_64-linux-gnu/libmicrohttpd.so /usr/lib/x86_64-linux-gnu/libxapian.so -Wl,--end-group
/usr/bin/ld: /usr/local/lib/x86_64-linux-gnu/libkiwix.so: undefined reference to `zim::Item::getPath[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

I suspect that commit/PR because https://github.com/openzim/libzim/commit/2a810acaddb9dc85224aa5222209fb92128f0159 compiles without any issues.

**Comment by mgautierfr** [comment]
Which version of kiwix-tools are you using ?
We have [switch to cpp17](https://github.com/kiwix/kiwix-tools/pull/636) so we shouldn't have a `[abi:cxx11]`.

**Comment by juuz0** [comment]
kiwix-tools is also the latest/main branch, i was compiling it on a new installation. Apologies for the late reply. Let me know if I need to provide other info.

**Comment by mgautierfr** [comment]
> c++  -o src/searcher/kiwix-search src/searcher/kiwix-search.p/kiwix-search.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-rpath,/usr/local/lib/x86_64-linux-gnu -Wl,-rpath-link,/usr/local/lib/x86_64-linux-gnu -pthread -Wl,--start-group /usr/local/lib/x86_64-linux-gnu/libkiwix.so /usr/local/lib/x86_64-linux-gnu/libzim.so /usr/lib/x86_64-linux-gnu/liblzma.so /usr/lib/x86_64-linux-gnu/libzstd.so /usr/lib/x86_64-linux-gnu/libicui18n.so /usr/lib/x86_64-linux-gnu/libicuuc.so /usr/lib/x86_64-linux-gnu/libicudata.so /usr/lib/x86_64-linux-gnu/libpugixml.so /usr/lib/x86_64-linux-gnu/libcurl.so /usr/lib/x86_64-linux-gnu/libmicrohttpd.so /usr/lib/x86_64-linux-gnu/libxapian.so -Wl,--end-group
/usr/bin/ld: /usr/local/lib/x86_64-linux-gnu/libkiwix.so: undefined reference to `zim::Item::getPath[abi:cxx11]() const'
collect2: error: ld returned 1 exit status

You are linking with a "installed" libkiwix, not the one currently being compiled (and tested here).

You probably have a already (old version) libkiwix installed.

**Comment by kelson42** [comment]
Yes, compilation/execution works with ubuntu 22.04. This is typically a sympton of linking against the wrong version of the library.
